### ISSUE TITLE
[Sugguestion]

### ISSUE THREAD

**Issue by Dvalin21** [Bytelake/Coral-in-LXC#2]
Hello.  Thanks for writing this, but something probably needs to be mention before doing all this.
All of this doesn't work unless you have enable the no subscription repos and others. I would suggest adding Proxmox VE Helper Script "Post Proxmox Install Script" by tteck https://tteck.github.io/Proxmox/   Then still once this is done and it has you reboot, run the following commands as the headers will need to be installed $ apt install pve-headers-$(uname -r)
Once all this is completed, then installing this and other packages will be a breeze. Thanks for your time.

**Comment by rantanplan1980** [comment]
Hallo zusammen,

Ich habe ein Thema mit einem LXC Container in dem ich FRIGATE laufen lassen möchte.
Frigate habe ich soweit installier und funktioniert mit folgender config.yaml

Config.yaml:

mqtt:
  host: 192.168.1.150
  user: Benutzername
  password: Passwort
#detectors:
#  coral:
#    type: edgetpu
#    device: usb
cameras:
  Kellerfrigate:
    ffmpeg:
      inputs:
        - path: rtsp://Benutzername:Passwort@192.168.1.240:554/h264Preview_01_sub
          roles:
            - detect
            - clips
            - record
    objects:
      track:
        - person
        - cat
        - dog
        - bird
    snapshots:
      enabled: True
      timestamp: True
      bounding_box: True
      retain:
        default: 2
    motion:
      mask:
        - 596,28,1280,91,1280,0,336,0


Das entsprechende LOG sieht glaub dann auch gut aus.

Nun hab ich meinen CORAL TPU an einen USB3 angeschlossen und bin ich wie folgt vorgegangen:

https://github.com/Bytelake/Coral-in-LXC (Danke für deine Anleitung)

Config hab ich auch entsprechend angepasst.

detectors:
  coral:
    type: edgetpu
    device: usb

Bekomme aber folgende Fehlermeldung:

023-10-01 10:09:30.664468146  [INFO] Starting Frigate...
2023-10-01 10:09:31.549576998  [2023-10-01 10:09:31] frigate.app                    INFO    : Starting Frigate (0.12.1-367d724)
2023-10-01 10:09:31.563690020  [2023-10-01 10:09:31] peewee_migrate                 INFO    : Starting migrations
2023-10-01 10:09:31.567443928  [2023-10-01 10:09:31] peewee_migrate                 INFO    : There is nothing to migrate
2023-10-01 10:09:31.580563362  [2023-10-01 10:09:31] detector.coral                 INFO    : Starting detection process: 420
2023-10-01 10:09:31.581223240  [2023-10-01 10:09:31] frigate.app                    INFO    : Output process started: 422
2023-10-01 10:09:31.582808157  [2023-10-01 10:09:31] frigate.detectors.plugins.edgetpu_tfl INFO    : Attempting to load TPU as usb
2023-10-01 10:09:31.583630039  [2023-10-01 10:09:31] frigate.detectors.plugins.edgetpu_tfl ERROR   : No EdgeTPU was detected. If you do not have a Coral device yet, you must configure CPU detectors.
2023-10-01 10:09:31.586401991  Process detector:coral:
2023-10-01 10:09:31.586404832  Traceback (most recent call last):
2023-10-01 10:09:31.586406198    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 160, in load_delegate
2023-10-01 10:09:31.586409310      delegate = Delegate(library, options)
2023-10-01 10:09:31.586411005    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 119, in __init__
2023-10-01 10:09:31.586424007      raise ValueError(capture.message)
2023-10-01 10:09:31.586425135  ValueError
2023-10-01 10:09:31.586426074  
2023-10-01 10:09:31.586427615  During handling of the above exception, another exception occurred:
2023-10-01 10:09:31.586428549  
2023-10-01 10:09:31.586429536  Traceback (most recent call last):
2023-10-01 10:09:31.586430663    File "/usr/lib/python3.9/multiprocessing/process.py", line 315, in _bootstrap
2023-10-01 10:09:31.586448141      self.run()
2023-10-01 10:09:31.586449419    File "/usr/lib/python3.9/multiprocessing/process.py", line 108, in run
2023-10-01 10:09:31.586450499      self._target(*self._args, **self._kwargs)
2023-10-01 10:09:31.586451592    File "/opt/frigate/frigate/object_detection.py", line 98, in run_detector
2023-10-01 10:09:31.586464632      object_detector = LocalObjectDetector(detector_config=detector_config)
2023-10-01 10:09:31.586465838    File "/opt/frigate/frigate/object_detection.py", line 52, in __init__
2023-10-01 10:09:31.586466986      self.detect_api = create_detector(detector_config)
2023-10-01 10:09:31.586468112    File "/opt/frigate/frigate/detectors/__init__.py", line 24, in create_detector
2023-10-01 10:09:31.586469110      return api(detector_config)
2023-10-01 10:09:31.586470235    File "/opt/frigate/frigate/detectors/plugins/edgetpu_tfl.py", line 37, in __init__
2023-10-01 10:09:31.586471355      edge_tpu_delegate = load_delegate("libedgetpu.so.1.0", device_config)
2023-10-01 10:09:31.586485756    File "/usr/lib/python3/dist-packages/tflite_runtime/interpreter.py", line 162, in load_delegate
2023-10-01 10:09:31.586486960      raise ValueError('Failed to load delegate from {}\n{}'.format(
2023-10-01 10:09:31.586488066  ValueError: Failed to load delegate from libedgetpu.so.1.0
2023-10-01 10:09:31.586489014  
2023-10-01 10:09:31.589209129  [2023-10-01 10:09:31] frigate.app                    INFO    : Camera processor started for Kellerfrigate: 425
2023-10-01 10:09:31.589213701  [2023-10-01 10:09:31] frigate.app                    INFO    : Capture process started for Kellerfrigate: 427
2023-10-01 10:09:31.591814018  [2023-10-01 10:09:31] frigate.comms.dispatcher       INFO    : Turning off detection for Kellerfrigate

root@frigate:~# lsusb
Bus 002 Device 001: ID 1d6b:0003 Linux Foundation 3.0 root hub
Bus 001 Device 003: ID 1a6e:089a Global Unichip Corp. 
Bus 001 Device 005: ID 8087:0aaa Intel Corp. Bluetooth 9460/9560 Jefferson Peak (JfP)
Bus 001 Device 001: ID 1d6b:0002 Linux Foundation 2.0 root hub


Kann mir jemand sagen wie ich hier eine Lösung finden kann.
Vielen Dank!
